/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projet;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author theor
 */
public class Categorie extends javax.swing.JPanel {

    /**
     * Creates new form Categorie
     */
    public Categorie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAfficherCategorie = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonAfficherProduit = new javax.swing.JButton();
        RetourMenu = new javax.swing.JButton();

        buttonAfficherCategorie.setForeground(new java.awt.Color(255, 102, 102));
        buttonAfficherCategorie.setText("Afficher les categories");
        buttonAfficherCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAfficherCategorieActionPerformed(evt);
            }
        });

        jList1.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        buttonAfficherProduit.setForeground(new java.awt.Color(255, 102, 102));
        buttonAfficherProduit.setText("Afficher le produit");
        buttonAfficherProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAfficherProduitActionPerformed(evt);
            }
        });

        RetourMenu.setText("Retour");
        RetourMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAfficherCategorie)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAfficherProduit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RetourMenu)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RetourMenu)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAfficherCategorie)
                    .addComponent(buttonAfficherProduit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAfficherCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAfficherCategorieActionPerformed

        DefaultListModel produit = (DefaultListModel) jList1.getModel();

        if(Main.connecter == 1){
            try {
                //            Statement requete = Connectt.connexion.createStatement();
                //            ResultSet lesDonnees = requete.executeQuery("select * from categorie");
                ResultSet lesDonnees = SqlManager.getInstance().requeteSelection("select * from categorie");
                produit.removeAllElements();
                while (lesDonnees.next()) {
                    String id = lesDonnees.getString("Id_categorie");
                    String libelle = lesDonnees.getString("libelle");

                    produit.addElement("ID: " + id + " " + libelle);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Veuillez vous identifier");
        }
    }//GEN-LAST:event_buttonAfficherCategorieActionPerformed

    private void buttonAfficherProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAfficherProduitActionPerformed
        DefaultListModel produit = (DefaultListModel) jList1.getModel();

        if(Main.connecter == 1){
            try {
                //            Statement requete = Connectt.connexion.createStatement();
                //            ResultSet lesDonnees = requete.executeQuery("select * from produit");
                //
                ResultSet lesDonnees = SqlManager.getInstance().requeteSelection("select * from produit");
                if (jList1.getSelectedValue() == null) {
                    JOptionPane.showMessageDialog(null, "Veuillez selectionner une categorie");
                    return;
                }
                String[] selected = jList1.getSelectedValue().split(" ");
                while (lesDonnees.next() ) {
                    if (selected[1].equalsIgnoreCase(lesDonnees.getString("Id_categorie"))) {
                        String libelle = "Type de cape: " + lesDonnees.getString("libellle");
                        String categorie = "Categorie: " + lesDonnees.getString ("categorie");
                        String prix = "Prix: " + lesDonnees.getString("prix") + " € unit";
                        String quantite = "Quantité: " + lesDonnees.getString("quantite") + " en stock";
                        String evaluation = "Evaluation: " + lesDonnees.getString("evaluation") + " ★";

                        produit.removeAllElements();
                        produit.addElement(libelle);
                        produit.addElement(categorie);
                        produit.addElement(prix);
                        produit.addElement(quantite);
                        produit.addElement(evaluation);
                    }

                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Veuillez vous identifier");
        }            // TODO add your handling code here:
    }//GEN-LAST:event_buttonAfficherProduitActionPerformed

    private void RetourMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourMenuActionPerformed
       Categorie fenetre = new Categorie();
       fenetre.setVisible(false);
       Main.Main.setVisible(true);
        
    }//GEN-LAST:event_RetourMenuActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RetourMenu;
    private javax.swing.JButton buttonAfficherCategorie;
    private javax.swing.JButton buttonAfficherProduit;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
