/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projet;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author theor
 */
public class Login extends javax.swing.JPanel {

    
    static Connection connexion;
    public String serveur;
    public String port;
    public String nomBDD;
    public String id;
    public String mdp;
    public static int connecter;
    public static boolean admin;
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        connect();
    }
    
    public void connect() {    
        
        //Initialisation des variables 
        String nomBDD = "test";
        String port = "80";
        String serveur = "jdbc:mysql://127.0.0.1:" + port + "/" + nomBDD;
        String id = "root";
        String mdp = "";



        try {
            Login.connexion = DriverManager.getConnection(serveur, id, mdp);
            System.out.println("Connecté");
        } catch (SQLException e) {
            System.out.println("Erreur de connexion");
        }      
        
    }

    public static void main(String[] args) {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeConnecter = new javax.swing.JButton();
        saisieLogin = new javax.swing.JTextField();
        saisieMotDePasse = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        SeConnecter.setText("Se connecter");
        SeConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeConnecterActionPerformed(evt);
            }
        });

        jLabel1.setText("Login");

        jLabel2.setText("Mot de passe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saisieLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saisieMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeConnecter))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saisieLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saisieMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(SeConnecter)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SeConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeConnecterActionPerformed
        try {
            
            ResultSet sql = SqlManager.getInstance().requeteSelection("select * from compteAgents where nomAgent = '" + saisieLogin.getText() + "' and motdepasseAgent = '" + saisieMotDePasse.getText() + "'");
            
//            Statement requete = connexion.createStatement();
//
//            ResultSet sql = requete.executeQuery("select * from compteAgents where nomAgent = '" + saisieLogin.getText() + "' and motdepasseAgent = '" + saisieMdp.getText() + "'");

            if (sql.next()) {

                int id = sql.getInt("id_profil");
                if (id <= 1) {
                    System.out.println(id);
                    JOptionPane.showMessageDialog(null, "Bienvenue " + sql.getString("nomAgent") + " vous etes Admin");
                    connecter = 1;
                    admin = true;
                    System.out.println("status admin true");
//                    champsAffichageProfil.setVisible(true);
//                    champsAffichageSession.setVisible(true);
//                    affichageProfil.setText("Admin");
//                    affichageSession.setText(sql.getString("nomAgent"));
                    
                    
                    
                    
                  



                } else {
                    System.out.println(id);
                    JOptionPane.showMessageDialog(null, "Bienvenue " + sql.getString("nomAgent") + " vous etes Agent");
                    connecter = 1;
                    admin = false;
                    System.out.println("status admin false");
//                    champsAffichageProfil.setVisible(true);
//                    champsAffichageSession.setVisible(true);
//                    affichageProfil.setText("Agent");
//                    affichageSession.setText(sql.getString("nomAgent"));

                }

            } else {
                JOptionPane.showMessageDialog(null, "Tu n'es pas dans la BDD");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SeConnecterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SeConnecter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField saisieLogin;
    private javax.swing.JTextField saisieMotDePasse;
    // End of variables declaration//GEN-END:variables
}
